# Dark theme (Dracula-inspired)
# Colors (class, border, background, text, indicator, child_border)
client.focused          #bd93f9 #44475a #f8f8f2 #bd93f9   #bd93f9
client.focused_inactive #44475a #44475a #f8f8f2 #44475a   #44475a
client.unfocused        #282a36 #282a36 #bfbfbf #282a36   #282a36
client.urgent           #44475a #ff5555 #f8f8f2 #ff5555   #ff5555
client.placeholder      #282a36 #282a36 #f8f8f2 #282a36   #282a36
client.background       #282a36


# wallpaper: dark.jpg
