bar {
    status_command i3blocks -c ~/.config/i3blocks/config
    position top

    font pango:JetBrainsMono Nerd Font 12

    colors {
        background #1a1b26    
        statusline #a9b1d6      
        separator  #444b6a     

        focused_workspace  #f7768e #1a1b26 #ffffff   
        active_workspace   #bd93f9 #1a1b26 #ffffff 
        inactive_workspace #444b6a #1a1b26 #a9b1d6   
        urgent_workspace   #ff4971 #1a1b26 #ffffff  
        binding_mode       #1a1b26 #bd93f9 #ffffff
    }
}
