[module/cava]
type = custom/script
exec = ~/.config/waybar/scripts/cava.sh
tail = true
interval = 0
label = %output%
format = <label>
format-padding = 1
; Pick a font index that’s monospaced if you use multiple fonts
; format-font = 2
; Optional styling
; format-foreground = ${colors.primary}
