[module/i3ws]
type = internal/i3

; usa solo el label-state
format = <label-state>

; mapping 1..10 -> chino
ws-icon-0 = 1;一
ws-icon-1 = 2;二
ws-icon-2 = 3;三
ws-icon-3 = 4;四
ws-icon-4 = 5;五
ws-icon-5 = 6;六
ws-icon-6 = 7;七
ws-icon-7 = 8;八
ws-icon-8 = 9;九
ws-icon-9 = 10;十
ws-icon-default = ·

; fuerza Unifont (font-3 => T4)
label-focused   = %{T4}%icon%%{T-}
label-unfocused = %{T4}%icon%%{T-}
label-visible   = %{T4}%icon%%{T-}
label-urgent    = %{T4}%icon%%{T-}

label-focused-background = ${colors.primary}
label-focused-foreground = ${colors.background}
label-focused-underline  = ${colors.primary}
label-focused-padding    = 1

label-unfocused-padding = 1
label-visible-padding   = 1
label-urgent-background = ${colors.error}
label-urgent-padding    = 1

label-separator = |
label-separator-foreground = ${colors.accent}
