[module/xwindow]
type = internal/xwindow
format = <label>

format-padding = 0

; Available tokens:
;   %title%
;   %instance% (first part of the WM_CLASS atom, new in version 3.7.0)
;   %class%    (second part of the WM_CLASS atom, new in version 3.7.0)
; Default: %title%
label = %title%
label-maxlen = 25

label-empty = Empty
label-empty-foreground = #707880
